olfactometer.Olfactometer:
    enable: IOHUB_BOOL
    name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True    

    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False    
    monitor_event_types:
        IOHUB_LIST:
            valid_values: [SerialInputEvent, SerialByteChangeEvent]
            min_length: 0
            max_length: 2
    event_buffer_length:
        IOHUB_INT:
            min: 1
            max: 2048    
    device_number: 0
    model_name:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    manufacturer_name:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    serial_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    manufacture_date: IOHUB_DATE
    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8    
    hardware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
